title = "Human Solutions"

# The URL the site will be built for
base_url = "https://human.solutions"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [{ name = "tags", rss = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
home_subtitle = "Open Source and Rust passionates"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/opensource", name = "Open Source" },
    { link = "/services", name = "Services" },
    { link = "/blog", name = "Blog" },
]

hermit_social = [
    { name = "Open Collective", link = "https://opencollective.com/human-solutions" },
    { name = "GitHub", link = "https://github.com/human-solutions" },
    { name = "Discord", link = "https://discord.gg/CV5ZDT9U5y" },
]

[extra.highlightjs]
enable = true
clipboard = false
theme = "vs2015"

[extra.author]
name = "Human Solutions"
